#!/usr/bin/env bash
set -Eeuo pipefail
echo "🚀 EXECUTION PLAN START — $(date)"
echo '▶ RUN /data/data/com.termux/files/home/.termux/boot/planetary_start.sh'
bash "/data/data/com.termux/files/home/.termux/boot/planetary_start.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/AiKre8tive_ONE/monorepo/tools/integrity_run.sh'
bash "/data/data/com.termux/files/home/AiKre8tive_ONE/monorepo/tools/integrity_run.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/PlanetaryAgents/bin/taskbox_runner.sh'
bash "/data/data/com.termux/files/home/PlanetaryAgents/bin/taskbox_runner.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/PlanetaryAgents/bin/start_stack.sh'
bash "/data/data/com.termux/files/home/PlanetaryAgents/bin/start_stack.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/PlanetaryAgents/bin/stop_stack.sh'
bash "/data/data/com.termux/files/home/PlanetaryAgents/bin/stop_stack.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/termux-scripts/git-sync.sh'
bash "/data/data/com.termux/files/home/termux-scripts/git-sync.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/termux-scripts/scripts/sync.sh'
bash "/data/data/com.termux/files/home/termux-scripts/scripts/sync.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/setup-termux-obsidian-sync.sh'
bash "/data/data/com.termux/files/home/setup-termux-obsidian-sync.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/sovereign_deployer.sh'
bash "/data/data/com.termux/files/home/sovereign_deployer.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/vault_sync.sh'
bash "/data/data/com.termux/files/home/vault_sync.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/obsidian_sync.sh'
bash "/data/data/com.termux/files/home/obsidian_sync.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/sync_to_obsidian.sh'
bash "/data/data/com.termux/files/home/sync_to_obsidian.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/sovereign_build.sh'
bash "/data/data/com.termux/files/home/sovereign_build.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/run_santa.sh'
bash "/data/data/com.termux/files/home/run_santa.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/run_all_home.sh'
bash "/data/data/com.termux/files/home/run_all_home.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/find_and_run_everything.sh'
bash "/data/data/com.termux/files/home/find_and_run_everything.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/run_monorepo.sh'
bash "/data/data/com.termux/files/home/run_monorepo.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/SOVEREIGN_SYSTEM/core/run.sh'
bash "/data/data/com.termux/files/home/SOVEREIGN_SYSTEM/core/run.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/SOVEREIGN_SYSTEM/core/wrap.sh'
bash "/data/data/com.termux/files/home/SOVEREIGN_SYSTEM/core/wrap.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/SOVEREIGN_SYSTEM/core/discover_termux.sh'
bash "/data/data/com.termux/files/home/SOVEREIGN_SYSTEM/core/discover_termux.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/SOVEREIGN_SYSTEM/core/bulk_wrap.sh'
bash "/data/data/com.termux/files/home/SOVEREIGN_SYSTEM/core/bulk_wrap.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/SOVEREIGN_SYSTEM/agents/example_agent.sh'
bash "/data/data/com.termux/files/home/SOVEREIGN_SYSTEM/agents/example_agent.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/STACK/run_stack.sh'
bash "/data/data/com.termux/files/home/STACK/run_stack.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/STACK/load_stacks.sh'
bash "/data/data/com.termux/files/home/STACK/load_stacks.sh" || true
echo '▶ RUN /data/data/com.termux/files/home/STACK/stack_up.sh'
bash "/data/data/com.termux/files/home/STACK/stack_up.sh" || true
echo '✅ EXECUTION PLAN COMPLETE'
