github.com:
    users:
        FacePrintPay:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: FacePrintPay
